# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"initialise_loader": "01-instagram-scraping.ipynb",
         "load_profile_posts": "01-instagram-scraping.ipynb",
         "post_to_date": "01-instagram-scraping.ipynb",
         "post_to_caption": "01-instagram-scraping.ipynb",
         "post_to_media_url": "01-instagram-scraping.ipynb",
         "extract_post_content": "01-instagram-scraping.ipynb",
         "retrieve_posts": "01-instagram-scraping.ipynb",
         "initialise_client": "02-whatsapp-integration.ipynb",
         "get_random_post": "02-whatsapp-integration.ipynb",
         "send_post": "02-whatsapp-integration.ipynb",
         "check_msg_status": "02-whatsapp-integration.ipynb",
         "download_and_save_posts": "03-pipeline.ipynb",
         "send_posts_to_recipients": "03-pipeline.ipynb",
         "retrieve_and_send_posts_pipeline": "03-pipeline.ipynb"}

modules = ["instagram.py",
           "whatsapp.py",
           "pipeline.py"]

doc_url = "https://AyrtonB.github.io/percypics/"

git_url = "https://github.com/AyrtonB/Percy-Pics"

def custom_doc_links(name): return None
