# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/03-pipeline.ipynb (unless otherwise specified).

__all__ = ['download_and_save_posts', 'send_posts_to_recipients', 'retrieve_and_send_posts_pipeline']

# Cell
from percypics import instagram, whatsapp

import os
import dotenv
from typing import Any

from dagster import execute_pipeline, pipeline, solid, Field

# Cell
@solid()
def download_and_save_posts(_, fp: str):
    loader = instagram.initialise_loader()
    df_posts = instagram.retrieve_posts(loader, fp)

    df_posts.to_csv(fp, index=False)

    return

@solid()
def send_posts_to_recipients(_, fp: str, num_mobs: int=5):
    client = whatsapp.initialise_client()

    wa_recipients = [os.getenv(f'MOB_{mob_num+1}') for mob_num in range(num_mobs)]

    for wa_recipient in wa_recipients:
        post = whatsapp.get_random_post(fp)
        message = whatsapp.send_post(client, post, wa_recipient)
        whatsapp.check_msg_status(client, message, wa_recipient)

    return

# Cell
@pipeline
def retrieve_and_send_posts_pipeline():
    download_and_save_posts()
    send_posts_to_recipients()

    return