name: update_and_send_posts
on:
  schedule:
  - cron: "0 7 * * 4"
  workflow_dispatch: 

jobs:
  miniconda:
    name: Miniconda ${{ matrix.os }}
    runs-on: "ubuntu-latest"
            
    steps:
      - name: Load in repo
        uses: actions/checkout@v2
    
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.7'
        
      - name: Running pipeline
        shell: bash
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          dagster pipeline execute -m percypics.pipeline -c pipeline_inputs.yaml
        env:
          INSTA_USER: ${{ secrets.INSTA_USER }}
          INSTA_PSWD: ${{ secrets.INSTA_PSWD }}
          TWILIO_SID: ${{ secrets.TWILIO_SID }}
          TWILIO_TOKEN: ${{ secrets.TWILIO_TOKEN }}
          MOB_1: ${{ secrets.MOB_1 }}
          MOB_2: ${{ secrets.MOB_2 }}
          MOB_3: ${{ secrets.MOB_3 }}
          MOB_4: ${{ secrets.MOB_4 }}
      
      - name: Saving changes to repo
        uses: stefanzweifel/git-auto-commit-action@v4
